here::i_am("r/future_pred.R")

library(here)
library(mgcv)
library(rjags)

library(future.apply)
plan(multicore, workers = 4)

save.plots <- FALSE

## BUG FILES RELATIVE POSITION IN REPO
load(here("data/test_data_ad.RData"))
load(here("data/postproc_ad.RData"))
load(here("data/postsim_ad.RData"))

fit <- as.matrix(fit)
beta.inds <- grep("beta", colnames(fit), fixed = TRUE)

############# IMPLEMENTATION DETAILS
yr <- rep(1995:2022, each = 4)
ag <- 1:52

############# PREDICTING INCIDENCE
## See the jagam help page.
## How to use the sim2jam function. Should be possible using the jags code generated by the jagam function and saved in a file
## together with the dummy data generated.
## would do prediction for this dummy data - but not sure it would give the matrix to enable it.

## Establish the jam object from which to do the prediction using the GAM model with the appropriate spline.
spl.basis <- "tp"
nq <- length(yr)
jags.data <- list(
    age = rep(ag, each = nq),
    yrs = rep(1:nq, times = max(ag)),
    D = runif(max(ag) * nq)
) ## Dummy data
jagam.gam <- jagam(as.formula(paste0("D ~ s(yrs, age, bs=spl.basis, k=80, m=2)")),
    family = Gamma(link = log),
    data = jags.data,
    file = here("bug/tps1_80_simjam.bug"),
    diagonalize = TRUE
) ## Set up the spline model, with a log-link function
jm.gam <- jags.model(here("bug/tps1_80_simjam.bug"), data = jagam.gam$jags.data, inits = jagam.gam$jags.ini, n.chains = 1, n.adapt = 0)
sam.gam <- jags.samples(jm.gam,
    "b",
    n.iter = 2,
    thin = 1
) ## Get a sample object containing at least two samples, into which we can place MCMC output
jam.gam <- sim2jam(sam.gam, jagam.gam$pregam) ## Get appopriate JAM object from which we can predict.

## Temporal point to which we want to extrapolate
extrap <- data.frame(
    yrs = rep(1:(nq + 32), times = max(ag)),
    age = rep(ag, each = nq + 32)
)

future.incidence <- function(n, inBeta, inJam, inDat) {
    inJam$coefficients <- inBeta[n, ]
    exp(mgcv:::predict.jam(inJam, newdata = inDat))
}

## There has possibly been some change in how jagam computes design matrices
## Consequence is that some elements of the matrix are -1x what they previously would have been.
## To be able to use the current jagam machinery, this can be achieved by similarly multiplying the relevant model parameters

## Find the columns that need switching
ind.minus1 <- which(zapsmall(stan.data$X - jam.gam$X)[1, ] != 0)
## Multiply relevant columns
betas <- fit[, beta.inds]
betas[, ind.minus1] <- -betas[, ind.minus1]

fv.gam <- future_lapply(1:nrow(betas), future.incidence, inBeta = betas, inJam = jam.gam, inDat = extrap, future.seed = TRUE)

rfv.gam <- future_lapply(fv.gam, function(x) rpois(length(x), x))
rfv.gam <- future_lapply(rfv.gam, array, dim = c(nq + 32, max(ag)), future.seed = TRUE)
rfv.gam.tot <- future_lapply(rfv.gam, function(x) apply(x, 1, sum), future.seed = TRUE)

## Aggregate over years
yr <- rep(1995:2030, each = 4)
rfv.gam.tot.byyear <- future_lapply(rfv.gam.tot, function(x) by(x, yr, sum), future.seed = TRUE)
rfv.gam.tot.byyear <- do.call(rbind, rfv.gam.tot.byyear)
qrfv.gam.tot.byyear <- apply(rfv.gam.tot.byyear, 2, quantile, probs = c(0.025, 0.5, 0.975))


qrfv.gam.tot.byyear <- qrfv.gam.tot.byyear[, colnames(qrfv.gam.tot.byyear) > "2008"]

require(ggplot2)
plot.ext <- ".pdf"
cd4.thresholds <- c(250, 50)

## barplot
gg.bar.cols <- c("gray44", "skyblue", "seagreen3", "brown4")
cols.to.plot.era2 <- cbind(2009:2030, c(gg.bar.cols[1], rep(gg.bar.cols[2], 2016 - 2010), rep(gg.bar.cols[3], 2023 - 2016), rep(gg.bar.cols[4], 2030 - 2022)))
df1 <- data.frame(
    "yrs" = 2009:2030,
    "infs" = qrfv.gam.tot.byyear[2, ],
    "lo" = qrfv.gam.tot.byyear[1, ],
    "hi" = qrfv.gam.tot.byyear[3, ],
    "col" = cols.to.plot.era2[, 2]
)

plcd4 <- list()
plyear <- list()
for (cd4 in cd4.thresholds)
{
    i <- which(cd4.thresholds == cd4)
    p <- ggplot(df1) +
        geom_bar(aes(x = yrs, y = infs), stat = "identity", fill = df1$col) +
        geom_errorbar(aes(x = yrs, ymin = lo, ymax = hi), width = 0.4, colour = "black", size = 1, linetype = "dashed") +
        scale_x_continuous(
            breaks = seq(2009, 2030, by = 3),
            labels = seq(2009, 2030, by = 3),
            limits = c(2008.5, 2030.5)
        ) +
        theme_classic() +
        ggtitle("Estimated and projected annual HIV incidence") +
        theme(
            plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
            axis.title = element_text(size = 12, face = "bold"),
            legend.position = "None"
        ) +
        labs(x = "Year", y = "#Infections") +
        geom_hline(yintercept = cd4, linetype = "dashed")

    if (save.plots) ggsave(paste0("Elim", cd4, plot.ext), plot = p)


    ## ## Probabilities of being less than 250
    if (!exists("rfv.future")) rfv.future <- rfv.gam.tot.byyear[, colnames(rfv.gam.tot.byyear) > "2018"]
    plcd4[[i]] <- apply(
        rfv.future,
        2,
        function(x) mean(x <= cd4)
    )
    ## Put into data.frame format
    plcd4[[i]] <- data.frame(
        yr = as.integer(names(plcd4[[i]])),
        prob = as.numeric(as.vector(plcd4[[i]]))
    )
    p.pct <- ggplot(plcd4[[i]]) +
        geom_bar(aes(x = yr, y = prob), stat = "identity", fill = "brown4") +
        scale_x_continuous(
            breaks = 2019:2030,
            limits = c(2018.5, 2030.5)
        ) +
        theme_classic() +
        ggtitle(paste("Probability of hitting a threshold of", cd4, "diagnoses per annum")) +
        theme(
            plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
            axis.title = element_text(size = 12, face = "bold"),
            legend.position = "None"
        ) +
        labs(x = "Year", y = "Probability")


    if (save.plots) ggsave(paste0("Pr", cd4, plot.ext), plot = p.pct)

    ## ## Year of hitting 250
    plyear[[i]] <- data.frame(
        yr = plcd4[[i]][, 1],
        barh = diff(c(0, plcd4[[i]][, 2]))
    )
    p.yr <- ggplot(plyear[[i]]) +
        geom_bar(aes(x = yr, y = barh), stat = "identity", fill = "mediumorchid4") +
        scale_x_continuous(
            breaks = 2019:2030,
            limits = c(2018.5, 2030.5)
        ) +
        theme_classic() +
        ggtitle(paste("Year of achieving", cd4, "diagnoses per year")) +
        theme(
            plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
            axis.title = element_text(size = 12, face = "bold"),
            legend.position = "None"
        ) +
        labs(x = "Year", y = "Probability")

    if (save.plots) ggsave(paste0("PrHit", cd4, plot.ext), plot = p.yr)
}
